# Generated by Django 4.0.5 on 2022-09-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glucose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField(verbose_name='Measurement Date')),
            ],
        ),
    ]
