# Generated by Django 4.0.5 on 2022-09-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diabetes', '0003_alter_glucose_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glucose',
            name='myUsers',
        ),
        migrations.AddField(
            model_name='glucose',
            name='myUsers',
            field=models.ManyToManyField(blank=True, null=True, to='Diabetes.myuser'),
        ),
    ]
