# Generated by Django 4.0.5 on 2022-09-02 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diabetes', '0004_remove_glucose_myusers_glucose_myusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glucose',
            name='myUsers',
        ),
        migrations.AddField(
            model_name='glucose',
            name='myUsers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Diabetes.myuser'),
        ),
        migrations.CreateModel(
            name='GlucoseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diabetes.glucose')),
                ('myUsers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diabetes.myuser')),
            ],
        ),
    ]
