# Generated by Django 4.0.5 on 2022-09-03 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diabetes', '0006_glucose_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glucose',
            name='myUsers',
        ),
        migrations.DeleteModel(
            name='GlucoseUser',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
